version: '3.7'

services:

    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - "27017"
        volumes:
            - mongoDB:/etc/mongo
        networks:
          - mernnetwork
        restart: always

    web:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./:/opt/node-server
            - /opt/node-server/node_modules
        networks:
          - mernnetwork
        command: npm run dev
        restart: always

volumes:
  mongoDB:

networks:
  mernnetwork:





